#pragma once
using std::shared_ptr;
using std::string;
using std::vector;
using std::map;
using std::set;
using std::ifstream;
using std::istringstream; 
using std::ostream;
using std::cout;
using std::cin;
