oobjects=TextQuery.h QueryResult.h Test.cpp \
		 ../StrBlob/StrBlob.h ../StrBlob/StrBlob.cpp ../StrBlob/StrBlobPtr.h ../StrBlob/StrBlobPtr.cpp
cobjects=Test.cpp ../StrBlob/StrBlob.cpp ../StrBlob/StrBlobPtr.cpp
atest: $(oobjects)
	g++ -o atest -g -Wall -std=c++11 \
		$(cobjects)
