HEADER_FILE_RELATIVE_PATH = ../../header
GPP_FLAGS = -std=c++11 \
            -g \
            -pedantic \
            -Wall \
            -Wno-unused-variable \
            -Wno-multichar \
            -I ${HEADER_FILE_RELATIVE_PATH}